In [21]:
import numpy as np

w1 = [3.19304864, 9.93278091, -4.74659947]
w2 = [-1.59451474, 9.97879746, 4.47953684]
V1 = [0.32620883, -8.71647388, 8.39004239]
X = [ [1,0,0], [1,0,1], [1,1,0], [1,1,1] ]
X1 = [1,0,0]

sig = lambda y : 1/(1+np.exp(-y))

forward propagation using nuerons

one input is processed at a time  

In [10]:
Z = [
1,# hard coded 1
# Neuron 1:
X1[0]*w1[0] +
X1[1]*w1[1] +
X1[2]*w1[2],
# Neuron 2:
X1[0]*w2[0] +
X1[1]*w2[1] +
X1[2]*w2[2]
]

print(Z)
Z = [1,sig(Z[1]),sig(Z[2])]
print(Z)

[1, 3.19304864, -1.59451474]
[1, 0.9605718456066229, 0.16874965243320605]


In [11]:
# Y output Neuron 1:

Y = Z[0]*V1[0] + Z[1]*V1[1] + Z[2]*V1[2]

print(Y)
Y = sig(Y)
print(Y)

-6.630773834881156
0.0013174040500717125


Perform forward propagation using matrices

multipe input or samples are calculated in one go

In [26]:
inputs = X
weights = [w1,w2]
zlayerout = np.dot(inputs, np.array(weights).T)
print(zlayerout)

#apply sig function to ouputs
for row, sample in enumerate(zlayerout):
    for col, w in enumerate(sample):
        zlayerout[row][col] = sig(w)

zlayerout = np.insert(zlayerout, 0, 1., axis=1)
print(zlayerout)

[[ 3.19304864 -1.59451474]
 [-1.55355083  2.8850221 ]
 [13.12582955  8.38428272]
 [ 8.37923008 12.86381956]]
[[1.         0.96057185 0.16874965]
 [1.         0.17457401 0.94710104]
 [1.         0.99999801 0.99977162]
 [1.         0.99977047 0.99999741]]


In [27]:
weights = V1

Youtput = np.dot(zlayerout, np.array(weights).T)
print(Youtput)

[-6.63077383e+00  6.75075691e+00 -2.12138330e-03  1.75633574e-03]
