In [1]:
import numpy as np

w1 = [3.19304864, 9.93278091, -4.74659947]
w2 = [-1.59451474, 9.97879746, 4.47953684]
V1 = [0.32620883, -8.71647388, 8.39004239]
X = [ [1,0,0], [1,0,1], [1,1,0], [1,1,1] ]
X1 = [1,0,0]

sig = lambda y : 1/(1+np.exp(-y))
dsig = lambda y : sig(y) * (1-sig(y))

# Forward Propagation

In [2]:
inputs = X
weights = [w1,w2]
zlayerout = np.dot(inputs, np.array(weights).T)
print(zlayerout)

#apply sig function to ouputs
for row, sample in enumerate(zlayerout):
    for col, w in enumerate(sample):
        zlayerout[row][col] = sig(w)

zlayerout = np.insert(zlayerout, 0, 1., axis=1)
print(zlayerout)

[[ 3.19304864 -1.59451474]
 [-1.55355083  2.8850221 ]
 [13.12582955  8.38428272]
 [ 8.37923008 12.86381956]]
[[1.         0.96057185 0.16874965]
 [1.         0.17457401 0.94710104]
 [1.         0.99999801 0.99977162]
 [1.         0.99977047 0.99999741]]


In [3]:
weights = V1
Youtput = np.dot(zlayerout, np.array(weights).T)
print(Youtput)

[-6.63077383e+00  6.75075691e+00 -2.12138330e-03  1.75633574e-03]


# Back Propagation

In [ ]:
training_data = [((0,0),0),((0,1),1),((1,0),1),((1,1),0)]
# X = [[1,0,0], [1,0,1], [1,1,0], [1,1,1]]
Y_training = [0, 1, 1, 0] 
