# Gilbert Barr assignment 2

In [20]:
import numpy as np

w1 = [3.19304864, 9.93278091, -4.74659947]
w2 = [-1.59451474, 9.97879746, 4.47953684]
V1 = [0.32620883, -8.71647388, 8.39004239]
X = [ [1,0,0], [1,0,1], [1,1,0], [1,1,1] ]
X1 = [1,0,0]

sig = lambda y : 1/(1+np.exp(-y))
dsig = lambda y : sig(y) * (1-sig(y))

MSE = lambda y_pred, y_true : np.mean((y_true - y_pred)**2, axis=-1)

def dMSE(y_pred,y_true):
    s = y_pred.size
    outputs = y_pred[0].size
    return (-2 * (y_true - y_pred)/outputs)/s

# Forward Propagation

In [23]:
inputs = X
weights = [w1,w2]
zlayerout = np.dot(inputs, np.array(weights).T)
print(zlayerout)

#apply sig function to ouputs
for row, sample in enumerate(zlayerout):
    for col, w in enumerate(sample):
        zlayerout[row][col] = sig(w)
zlayerout_nsig = zlayerout
zlayerout = np.insert(zlayerout, 0, 1., axis=1)
print(zlayerout)

[[ 3.19304864 -1.59451474]
 [-1.55355083  2.8850221 ]
 [13.12582955  8.38428272]
 [ 8.37923008 12.86381956]]
[[1.         0.96057185 0.16874965]
 [1.         0.17457401 0.94710104]
 [1.         0.99999801 0.99977162]
 [1.         0.99977047 0.99999741]]


In [6]:
weights = V1
Youtput = np.dot(zlayerout, np.array(weights).T)
print(Youtput)

[-6.63077383e+00  6.75075691e+00 -2.12138330e-03  1.75633574e-03]


# Back Propagation

In [43]:

training_data = [((0,0),0),((0,1),1),((1,0),1),((1,1),0)]
# X = [[1,0,0], [1,0,1], [1,1,0], [1,1,1]]
Y_training = [0, 1, 1, 0] 


MSE(Youtput,Y_training)
loss_gradient = dMSE(Youtput,Y_training)
#print(loss_gradient)
#print(dsig(zlayerout_nsig))
#z_gradient = loss_gradient * dsig(zlayerout_nsig).T
print(loss_gradient)

#dinput = np.dot(z_gradient,np.array(V1).T)

[-3.31538692e+00  2.87537845e+00 -5.01060692e-01  8.78167872e-04]
